FROM ghcr.io/make87/python3-dev:latest

## Custom Add-ons

RUN apt-get update \
    && apt-get install --no-install-suggests --no-install-recommends -y \
        ffmpeg \
        vainfo \
        intel-media-va-driver \
        i965-va-driver \
        libva2 \
        libva-drm2 \
        libva-glx2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && true

